version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
  prefix: deps(actions)
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
  prefix: deps(actions)
